---

language: python
python: 3.4
env:
  - TOX_ENV=pypy-1.8.X
  - TOX_ENV=py34-1.8.X
  - TOX_ENV=py33-1.8.X
  - TOX_ENV=py32-1.8.X
  - TOX_ENV=py27-1.8.X
install:
  - pip install coveralls
  - pip install tox
script:
  - tox -e $TOX_ENV -- --with-coverage --cover-package=flatcontent
  - coverage report -m
after_success:
  coveralls --verbose
