---

language: python
python: 3.3
env:
  - TOX_ENV=pypy-1.6.X
  - TOX_ENV=pypy-1.5.X
  - TOX_ENV=pypy-1.4.X
  - TOX_ENV=py33-1.6.X
  - TOX_ENV=py33-1.5.X
  - TOX_ENV=py32-1.6.X
  - TOX_ENV=py32-1.5.X
  - TOX_ENV=py27-1.6.X
  - TOX_ENV=py27-1.5.X
  - TOX_ENV=py27-1.4.X
  - TOX_ENV=py26-1.6.X
  - TOX_ENV=py26-1.5.X
  - TOX_ENV=py26-1.4.X
install:
  - pip install coveralls
  - pip install tox
script:
  - tox -e $TOX_ENV -- --with-coverage --cover-package=flatcontent
  - coverage report -m
after_success:
  coveralls --verbose
